### ISSUE TITLE
您好，我看到您的代码里关于上行下行速率依然是通过随机数的形式来体现的？您对这个问题怎么考虑的呢？

### ISSUE THREAD

**Issue by xizhulove** [sling0318/Multi-Agent-Mec_Offloading-Use_DRL#1]
您好，我看到您的代码里关于上行下行速率依然是通过随机数的形式来体现的？您对这个问题怎么考虑的呢？

**Comment by sling0318** [comment]
这个问题我是做了一个简化考虑，并没有很严格的去写这个环境，我考虑的是一个任务在一个时隙中完成，然后下一个时隙的数值就用这个时隙的值进行一个随机的加减来达到不同的效果，目前也在写一个更严谨的环境。
