### ISSUE TITLE
然后您的代码时间成本那里应该用max求更大的值，好像不应该直接相加，然后我这边跑出来的结果还没有纯mec好

### ISSUE THREAD

**Issue by xizhulove** [sling0318/Multi-Agent-Mec_Offloading-Use_DRL#3]

**Comment by sling0318** [comment]
谢谢，意思是在边缘服务器上和本地计算的时间取最大的时间值是吗，第二个问题应该是我这个环境的问题，我只考虑了传输的延迟，并没有考虑传输的能耗，这样子就导致了到边缘节点上的能耗更低，数值设置上应该也有一部分问题，我会慢慢改进的。

**Comment by sling0318** [comment]
我发现问题所在了，我查看细看了一下延迟和能耗，我发现在延迟表现下MADDPG是要比MEC好的，在能耗方面MEC是要比MADDPG要低的，而且我综合考虑的那个分配的权重有点问题，能耗的占比系数非常大。

**Comment by xizhulove** [comment]
@sling0318 我也是研究这个方向的，您要是愿意，咱们可以留个联系方式，以后可以经常讨论

**Comment by skyknights** [comment]
@sling0318 您好，请问你目前的代码用maddpg效果好于其他算法吗？

**Comment by skyknights** [comment]
@xizhulove  您好，请问您在这方面有什么想法呢？  我也是研究这个方向的  可以相互联系 qq 1121269990
